# App name
spring.application.name=chat-application

#Application specific properties
app.api-version=v1

# Hibernate specific properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# MySQL specific properties
spring.datasource.url=jdbc:mysql://localhost:3306/chat_db?useTimezone=true&serverTimezone=Africa/Lagos
spring.datasource.username=root
spring.datasource.password=Ezedev98@


# Server Port number specific properties
app.base-url=http://localhost:3030

server.port=3030

file.upload-dir=/private/tmp/uploads/
app.title=api/${app.api-version}